name: Release

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Do a dry run to preview instead of a real release"
        required: true
        default: "true"

jobs:
  authorize:
    name: Authorize
    runs-on: macos-15
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: octokit/request-action@89697eb6635e52c6e1e5559f15b5c91ba5100cb0 # v2.1.9
        with:
          route: GET /repos/:repository/collaborators/${{ github.actor }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: macos-15
    needs: [authorize]
    strategy:
      matrix:
        ruby-version: ["2.7"]
        node-version: ["16.x"]
    steps:
      - name: Checkout Amplitude-iOS
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set Xcode 16.1
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.1.app

      - name: Install Apple platform SDKs
        run: |
          # Warm up CoreSimulator to avoid "Unable to connect to simulator":
          # https://github.com/actions/runner-images/issues/12862#issuecomment-3239326872
          xcrun simctl list > /dev/null
          sudo xcodebuild -downloadPlatform iOS
          sudo xcodebuild -downloadPlatform tvOS
          sudo xcodebuild -downloadPlatform watchOS
          sudo xcodebuild -downloadPlatform visionOS

      - name: Carthage Bootstrap
        run: carthage bootstrap --use-xcframeworks

      - name: Setup Ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install Cocoapods
        run: |
          gem install bundler -v 2.4.22
          bundle config path vendor/bundle
          bundle install
          pod install

      - name: iOS Tests
        run: |
          xcodebuild test \
            -workspace Amplitude.xcworkspace \
            -scheme Amplitude_iOSTests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16'

      # - name: macOS Tests @TODO Fix flaky macOS tests and re-enable
      #   run: |
      #     xcodebuild \
      #       -workspace Amplitude.xcworkspace \
      #       -scheme Amplitude_macOS \
      #       -sdk macosx \
      #       -destination 'platform=macosx' \
      #       test

      - name: tvOS Tests
        run: |
          xcodebuild \
            -workspace Amplitude.xcworkspace \
            -scheme Amplitude_tvOS \
            -sdk appletvsimulator \
            -destination 'platform=tvOS Simulator,name=Apple TV' \
            test

      - name: Validate Podfile
        run: pod lib lint --verbose

      - name: Setup Node.js
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout Amplitude-iOS gh-pages for building docs
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          ref: "gh-pages"
          path: "Amplitude-iOS-gh-pages"

      - name: Install appledoc binary
        run: |
          git clone https://github.com/amplitude/appledoc
          cd appledoc/
          sudo sh install-appledoc.sh
          cd ../
          sudo rm -rf appledoc/

      - name: Semantic Release --dry-run
        if: ${{ github.event.inputs.dryRun == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          GIT_AUTHOR_NAME: amplitude-sdk-bot
          GIT_AUTHOR_EMAIL: amplitude-sdk-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: amplitude-sdk-bot
          GIT_COMMITTER_EMAIL: amplitude-sdk-bot@users.noreply.github.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @google/semantic-release-replace-plugin@1.2.0 \
          -p @semantic-release/exec@5 \
          semantic-release --dry-run

      - name: Semantic Release
        if: ${{ github.event.inputs.dryRun == 'false'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
          GIT_AUTHOR_NAME: amplitude-sdk-bot
          GIT_AUTHOR_EMAIL: amplitude-sdk-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: amplitude-sdk-bot
          GIT_COMMITTER_EMAIL: amplitude-sdk-bot@users.noreply.github.com
        run: |
          npx \
          -p lodash \
          -p semantic-release@17 \
          -p @semantic-release/changelog@5 \
          -p @semantic-release/git@9 \
          -p @google/semantic-release-replace-plugin@1.2.0 \
          -p @semantic-release/exec@5 \
          semantic-release
